# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('age', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
