# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171103_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
