# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20171103_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('path', models.CharField(max_length=64)),
                ('desc', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
