# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_hobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='desc',
            new_name='time_begin',
        ),
    ]
