# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20171104_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('second_name', models.CharField(max_length=64)),
                ('age', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
