# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_organization_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='path',
            new_name='path_logo',
        ),
    ]
