# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20171105_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='path_logo',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='time_begin',
        ),
    ]
