# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='main_app.Organization', unique=True),
        ),
    ]
